neo4j:
  name: neo4j-kind
  edition: enterprise
  acceptLicenseAgreement: "yes"

  core:
    numberOfServers: 3
    persistentVolume:
      enabled: true
      size: 5Gi

  readReplica:
    numberOfServers: 0

service:
  type: ClusterIP

config:
  dbms.mode: CORE
  dbms.default_listen_address: 0.0.0.0

volumes:
  data:
    mode: defaultStorageClass

