neo4j:
  name: neo4j-kind
  edition: enterprise
  acceptLicenseAgreement: "yes"

cluster:
  enabled: true
  members: 3

config:
  dbms.mode: CORE
  dbms.default_listen_address: 0.0.0.0

service:
  type: ClusterIP

volumes:
  data:
    mode: defaultStorageClass
    size: 5Gi

